version: "3.8"

services:
  api:
    image: bigjames3/api-todo-liste:latest   # ⚠️ remplace par TON namespace exact
    container_name: api-todo-liste
    restart: always
    ports:
      - "80:3000"
