version: "3.8"

services:
  api:
    # Build le conteneur à partir du Dockerfile
    build: .
    # Map le port du conteneur vers l’hôte
    ports:
      - "3000:3000"
    # Synchronise les fichiers locaux avec le conteneur
    volumes:
      - .:/app
      - /app/node_modules
    # Relance l'app s'il y a un crash
    restart: unless-stopped
